eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: sendemail-server
  mail:
    host: smtp.qq.com
    username: 1228493283@qq.com
    password: ***
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true