eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: message-server

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000